[project]
name = "market-place-map"
version = "0.1.0"
description = "Telegram bot and interactive map for market stall discovery"
readme = "README.md"
authors = [
    { name = "Serhii Paiiuk"}
]
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.10.0",
    "aiogram>=3.30.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.14.2",
    "tortoise-orm[asyncpg]>=1.1.7",
    "uvicorn>=0.52.1",
]

[tool.uv]
package = false